use std::collections::BTreeMap;

use thiserror::Error;

use crate::domain::{PriceTicks, TradeSide};

/// Default participation fraction for newly arriving marketable size at a touch.
pub const DEFAULT_FILL_RATIO_PER_TOUCH: f64 = 0.2;

/// A resting paper order. V1 accepts buy orders only.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PaperOrder {
    pub id: u64,
    pub side: TradeSide,
    pub price: PriceTicks,
    pub size: u64,
    pub placed_at_ms: i64,
}

impl PaperOrder {
    /// Builds a valid V1 paper order.
    pub fn new(
        id: u64,
        side: TradeSide,
        price: PriceTicks,
        size: u64,
        placed_at_ms: i64,
    ) -> Result<Self, PaperError> {
        let order = Self {
            id,
            side,
            price,
            size,
            placed_at_ms,
        };
        order.validate()?;
        Ok(order)
    }

    fn validate(&self) -> Result<(), PaperError> {
        if self.side != TradeSide::Buy {
            return Err(PaperError::InvalidSide { side: self.side });
        }
        if self.size == 0 {
            return Err(PaperError::InvalidSize);
        }
        if self.price.as_micros() == 0 {
            return Err(PaperError::ZeroPrice);
        }
        Ok(())
    }
}

/// A fill generated by a resting paper order.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PaperFill {
    pub order_id: u64,
    pub price: PriceTicks,
    pub size: u64,
    pub filled_at_ms: i64,
    pub maker: bool,
}

/// One synthetic top-of-book observation and its newly arriving aggressive flow.
///
/// `bid_size` and `ask_size` describe displayed top-level depth. `marketable_size`
/// is the newly arriving flow used by the touch queue model; it is deliberately
/// separate from displayed depth so a replay can distinguish a quote update from
/// an execution event.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TopOfBookUpdate {
    pub at_ms: i64,
    pub best_bid: Option<PriceTicks>,
    pub bid_size: u64,
    pub best_ask: Option<PriceTicks>,
    pub ask_size: u64,
    pub marketable_size: u64,
}

impl TopOfBookUpdate {
    /// Creates a synthetic top-of-book update.
    #[must_use]
    pub const fn new(
        at_ms: i64,
        best_bid: Option<PriceTicks>,
        bid_size: u64,
        best_ask: Option<PriceTicks>,
        ask_size: u64,
        marketable_size: u64,
    ) -> Self {
        Self {
            at_ms,
            best_bid,
            bid_size,
            best_ask,
            ask_size,
            marketable_size,
        }
    }
}

/// Errors raised before a paper order can enter the resting book.
#[derive(Debug, Error, PartialEq)]
pub enum PaperError {
    #[error("paper V1 supports BUY orders only; got {side:?}")]
    InvalidSide { side: TradeSide },
    #[error("paper order size must be greater than zero")]
    InvalidSize,
    #[error("paper order price must be greater than zero")]
    ZeroPrice,
    #[error("fill ratio per touch must be finite and in [0, 1]")]
    InvalidFillRatio,
    #[error("paper order {0} is already resting")]
    DuplicateOrderId(u64),
}

#[derive(Debug, Clone, Copy)]
struct RestingOrder {
    order: PaperOrder,
    remaining_size: u64,
    touch_count: u64,
}

#[derive(Debug, Clone, Copy)]
enum FillCause {
    TradeThrough,
    Touch,
}

/// Synchronous paper matcher for resting maker orders.
///
/// The queue model is intentionally explicit and deterministic:
///
/// - A buy is trade-through eligible only when the synthetic best ask is
///   strictly below the order price. Displayed ask size is consumed FIFO by
///   price priority and then placement time.
/// - At a touch, `marketable_size * fill_ratio_per_touch` is the available
///   queue allocation for that update. It is distributed FIFO among orders at
///   the best bid, so a touch never means an automatic full fill.
/// - The first touch of an order is capped to leave one base unit when the
///   calculated allocation would otherwise fill it completely. Later touches
///   may complete the remaining queue. Cancellations remove the order at once.
///
/// There is no clock or I/O: callers supply every timestamp and every update.
pub struct PaperBook {
    fill_ratio_per_touch: f64,
    resting: BTreeMap<u64, RestingOrder>,
}

impl Default for PaperBook {
    fn default() -> Self {
        Self::with_default_fill_ratio()
    }
}

impl PaperBook {
    /// Creates a paper book with an explicit touch participation ratio.
    pub fn new(fill_ratio_per_touch: f64) -> Result<Self, PaperError> {
        if !fill_ratio_per_touch.is_finite() || !(0.0..=1.0).contains(&fill_ratio_per_touch) {
            return Err(PaperError::InvalidFillRatio);
        }
        Ok(Self {
            fill_ratio_per_touch,
            resting: BTreeMap::new(),
        })
    }

    /// Creates a paper book using the named V1 default ratio.
    pub fn with_default_fill_ratio() -> Self {
        Self::new(DEFAULT_FILL_RATIO_PER_TOUCH).expect("the named default fill ratio must be valid")
    }

    /// Returns the configured touch participation ratio.
    #[must_use]
    pub const fn fill_ratio_per_touch(&self) -> f64 {
        self.fill_ratio_per_touch
    }

    /// Places a validated order into the resting book without matching it.
    pub fn place(&mut self, order: PaperOrder) -> Result<(), PaperError> {
        order.validate()?;
        if self.resting.contains_key(&order.id) {
            return Err(PaperError::DuplicateOrderId(order.id));
        }
        self.resting.insert(
            order.id,
            RestingOrder {
                order,
                remaining_size: order.size,
                touch_count: 0,
            },
        );
        Ok(())
    }

    /// Cancels a resting order immediately. Returns whether it was present.
    pub fn cancel(&mut self, order_id: u64) -> bool {
        self.resting.remove(&order_id).is_some()
    }

    /// Returns whether an order is still resting.
    #[must_use]
    pub fn is_resting(&self, order_id: u64) -> bool {
        self.resting.contains_key(&order_id)
    }

    /// Returns the number of orders still resting.
    #[must_use]
    pub fn resting_count(&self) -> usize {
        self.resting.len()
    }

    /// Replays a complete synthetic tape in order and returns all generated fills.
    pub fn replay(&mut self, updates: &[TopOfBookUpdate]) -> Vec<PaperFill> {
        updates
            .iter()
            .flat_map(|update| self.apply_update(*update))
            .collect()
    }

    /// Applies one synthetic top-of-book update and returns fills from that update.
    pub fn apply_update(&mut self, update: TopOfBookUpdate) -> Vec<PaperFill> {
        let crossed_ids = self.ordered_ids(|resting| {
            update
                .best_ask
                .is_some_and(|best_ask| best_ask < resting.order.price)
        });
        let mut fills = Vec::new();
        let mut available_ask_size = update.ask_size;

        for order_id in &crossed_ids {
            if available_ask_size == 0 {
                break;
            }
            if let Some(fill) = self.fill_order(
                *order_id,
                available_ask_size,
                update.at_ms,
                FillCause::TradeThrough,
            ) {
                available_ask_size = available_ask_size.saturating_sub(fill.size);
                fills.push(fill);
            }
        }

        let touch_capacity = self.touch_capacity(update.marketable_size);
        if touch_capacity == 0 {
            return fills;
        }

        let best_bid = update.best_bid;
        let touch_ids = self.ordered_ids(|resting| {
            best_bid == Some(resting.order.price) && !crossed_ids.contains(&resting.order.id)
        });
        let mut available_touch_size = touch_capacity;

        for order_id in touch_ids {
            if available_touch_size == 0 {
                break;
            }
            if let Some(fill) = self.fill_order(
                order_id,
                available_touch_size,
                update.at_ms,
                FillCause::Touch,
            ) {
                available_touch_size = available_touch_size.saturating_sub(fill.size);
                fills.push(fill);
            }
        }

        fills
    }

    fn touch_capacity(&self, marketable_size: u64) -> u64 {
        (marketable_size as f64 * self.fill_ratio_per_touch).floor() as u64
    }

    fn ordered_ids<F>(&self, mut matches: F) -> Vec<u64>
    where
        F: FnMut(&RestingOrder) -> bool,
    {
        let mut orders: Vec<&RestingOrder> = self
            .resting
            .values()
            .filter(|order| matches(order))
            .collect();
        orders.sort_by(|left, right| {
            right
                .order
                .price
                .cmp(&left.order.price)
                .then_with(|| left.order.placed_at_ms.cmp(&right.order.placed_at_ms))
                .then_with(|| left.order.id.cmp(&right.order.id))
        });
        orders.into_iter().map(|resting| resting.order.id).collect()
    }

    fn fill_order(
        &mut self,
        order_id: u64,
        available_size: u64,
        filled_at_ms: i64,
        cause: FillCause,
    ) -> Option<PaperFill> {
        let (fill, complete) = {
            let resting = self.resting.get_mut(&order_id)?;
            let mut fill_size = available_size.min(resting.remaining_size);

            if matches!(cause, FillCause::Touch) {
                if resting.touch_count == 0 && fill_size >= resting.remaining_size {
                    fill_size = resting.remaining_size.saturating_sub(1);
                }
                resting.touch_count = resting.touch_count.saturating_add(1);
            }

            if fill_size == 0 {
                return None;
            }

            resting.remaining_size -= fill_size;
            (
                PaperFill {
                    order_id,
                    price: resting.order.price,
                    size: fill_size,
                    filled_at_ms,
                    maker: true,
                },
                resting.remaining_size == 0,
            )
        };

        if complete {
            self.resting.remove(&order_id);
        }
        Some(fill)
    }
}

/// Returns a buy-side markout in percentage points.
///
/// Kept as the V1 buy-side alias; use [`signed_markout`] when the side is
/// carried explicitly.
#[must_use]
pub fn markout(fill_price: PriceTicks, mid_at_horizon: PriceTicks) -> f64 {
    signed_markout(TradeSide::Buy, fill_price, mid_at_horizon)
}

/// Returns a side-signed markout in percentage points.
///
/// BUY YES: `future_price - fill_price`. SELL (or an equivalent short YES
/// exposure): `fill_price - future_price`, so the sign always matches the
/// economic PnL direction of the position.
#[must_use]
pub fn signed_markout(side: TradeSide, fill_price: PriceTicks, mid_at_horizon: PriceTicks) -> f64 {
    let move_pp = (mid_at_horizon.to_f64() - fill_price.to_f64()) * 100.0;
    match side {
        TradeSide::Buy => move_pp,
        TradeSide::Sell => -move_pp,
    }
}
